### ISSUE TITLE
Compression Algorithm 

### ISSUE THREAD

**Issue by JustNunuz** [AliceWonderland/hacktoberfest#10020]
Create a compression algorithm

**Comment by Aryaman047** [comment]
> Create a compression algorithm

Can you please detail the type of data and the language to be used for this, sir because I would like to contribute to it with my knowledge in it

**Comment by kartikey-katara-sn11** [comment]
Hello Sir!
please assigned me this issue.

**Comment by JustNunuz** [comment]
> and the language to be used for this, sir because I woul

Any language is fine. Just add a program to demonstrate the compression of data in some data structure (array,etc)

**Comment by kartikey-katara-sn11** [comment]
// Java Program to demonstrate
// Object Compression

import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.io.Serializable;
import java.util.zip.GZIPOutputStream;
import java.io.File;

public class GFG {

	public static void main(String args[])
	{

		// Creating objects of Java Class Bill
		Bill b1
			= new Bill("176BU", "Abhishek Gupta");
		Bill b2
			= new Bill("176DA", "Sushant Singh");
		FileOutputStream f = null;

		// Creates a GZIPOutputStream and
		// initialize it with null
		GZIPOutputStream g = null;

		// Creates an ObjectOutputStream and
		// initialise it with null
		// ObjectOutputStream writes to the
		// defined GZIPOutputStream.
		ObjectOutputStream o = null;

		// Write path of the file in the argument
		File newFile
			= new File("File.dat");
		try {

			// Pass the File object
			// (newFile) to the
			// FileOutputStream
			f = new FileOutputStream(newFile);
			g = new GZIPOutputStream(f);

			// Now pass the GZIPOutputStream object
			// to the ObjectOutputStream
			o = new ObjectOutputStream(g);

			// Writes the object that are going
			// to be compressed to the
			// ObjectOutputStream using
			// writeObject(objectName)
			o.writeObject(b1);
			o.writeObject(b2);

			// flush() API methods of
			// ObjectOutputStream.
			o.flush();
			System.out.println(
				"Process done..");
			System.out.println(
				"Objects are compressed");
		}
		catch (
			FileNotFoundException e) {

			// Catch Block
			System.out.println(
				e.message());
		}
		catch (IOException e) {

			// Catch Block
			System.out.println(
				e.message());
		}
		finally {
			try {

				// Using their
				// close() API methods,
				// closes both
				// the GZIPOutputStream
				// and the
				// ObjectOutputStream
				if (o != null)
					o.close();
				if (g != null)
					g.close();
			}
			catch (Exception ex) {

				// Catch block
				System.out.println(
					ex.message());
			}
		}
	}
}

class Bill implements Serializable {

	// Declaring the private variables
	private String billno;
	private String buyerName;

	// Creating constructor
	// of Java Class Bill
	public Bill(
		String bill, String buyer)
	{
		this.billno = bill;
		this.buyerName = buyer;
	}

	// Defining methods initializing
	// variables billno and buyerName
	public String getBill()
	{
		return billno;
	}
	public void setBill(
		String billno)
	{
		this.billno = billno;
	}
	public String getBuyerName()
	{
		return buyerName;
	}
	public void setBuyerName(
		String buyer)
	{
		this.buyerName = buyer;
	}
}

**Comment by kartikey-katara-sn11** [comment]
// Java Program to demonstrate
// Object Compression

import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.io.Serializable;
import java.util.zip.GZIPOutputStream;
import java.io.File;

public class Solution {

	public static void main(String args[])
	{

		// Creating objects of Java Class Bill
		Bill b1
			= new Bill("176BU", "Abhishek Gupta");
		Bill b2
			= new Bill("176DA", "Sushant Singh");
		FileOutputStream f = null;

		// Creates a GZIPOutputStream and
		// initialize it with null
		GZIPOutputStream g = null;

		// Creates an ObjectOutputStream and
		// initialise it with null
		// ObjectOutputStream writes to the
		// defined GZIPOutputStream.
		ObjectOutputStream o = null;

		// Write path of the file in the argument
		File newFile
			= new File("File.dat");
		try {

			// Pass the File object
			// (newFile) to the
			// FileOutputStream
			f = new FileOutputStream(newFile);
			g = new GZIPOutputStream(f);

			// Now pass the GZIPOutputStream object
			// to the ObjectOutputStream
			o = new ObjectOutputStream(g);

			// Writes the object that are going
			// to be compressed to the
			// ObjectOutputStream using
			// writeObject(objectName)
			o.writeObject(b1);
			o.writeObject(b2);

			// flush() API methods of
			// ObjectOutputStream.
			o.flush();
			System.out.println(
				"Process done..");
			System.out.println(
				"Objects are compressed");
		}
		catch (
			FileNotFoundException e) {

			// Catch Block
			System.out.println(
				e.message());
		}
		catch (IOException e) {

			// Catch Block
			System.out.println(
				e.message());
		}
		finally {
			try {

				// Using their
				// close() API methods,
				// closes both
				// the GZIPOutputStream
				// and the
				// ObjectOutputStream
				if (o != null)
					o.close();
				if (g != null)
					g.close();
			}
			catch (Exception ex) {

				// Catch block
				System.out.println(
					ex.message());
			}
		}
	}
}

class Bill implements Serializable {

	// Declaring the private variables
	private String billno;
	private String buyerName;

	// Creating constructor
	// of Java Class Bill
	public Bill(
		String bill, String buyer)
	{
		this.billno = bill;
		this.buyerName = buyer;
	}

	// Defining methods initializing
	// variables billno and buyerName
	public String getBill()
	{
		return billno;
	}
	public void setBill(
		String billno)
	{
		this.billno = billno;
	}
	public String getBuyerName()
	{
		return buyerName;
	}
	public void setBuyerName(
		String buyer)
	{
		this.buyerName = buyer;
	}
}
