### ISSUE TITLE
Add a JS Calculator to the project.

### ISSUE THREAD

**Issue by MysteryHawk17** [AliceWonderland/hacktoberfest#10210]
HIi @AliceWonderland  I want to add a new JS calculator to the codebase. Please assign this issue to me .

**Comment by Parth-2609** [comment]
heyy please assign this issue to me under the Hacktoberfest tag
<img width="272" alt="image" src="https://user-images.githubusercontent.com/103762350/195696191-13be50bd-8381-4719-a7c9-8943d77d790a.png">

**Comment by SnehaDeshmukh28** [comment]
Heyy!! @AliceWonderland. I would love to add the JS Calculator to the project. Can you please assign that to me.

**Comment by Serajhub** [comment]
can you assign this issue to me?

**Comment by CODER-AsHuToSh** [comment]
Hello, Can you please assign this issue to me?

**Comment by srvjha** [comment]
Can u please assign the issue to me ? I can create an multi-dimensional calculator which can perform both Normal as well as Scientific calculations

**Comment by Serajhub** [comment]
Can u please assign the issue to me . I can create JS  calculator .

**Comment by arij33tt** [comment]
@AliceWonderland

Can you please assign the issue to me . I created  JS calculator . you can have a look through this screenshot  or 
try it out 

[Github ](https://github.com/arij33tt/vanilla_js_calculator) 


 [screenshot](https://github.com/arij33tt/vanilla_js_calculator/blob/master/ss_calc.jpg)

**Comment by SanskarJain007** [comment]
@AliceWonderland Can you please assign this issue to me. I would love to contribute.
Link for the project : -
codepen link: - https://codepen.io/sanskarjain007/pen/ZExqyVW

**Comment by theshubhamgour** [comment]
Could you assign me this issue?

**Comment by Rehanpasha732** [comment]
please assign me

**Comment by soham1826** [comment]
Hey @AliceWonderland  i would love to add  this Javascript Calculator , i will add the calculator that can satisfy most of the needs 
please assign this project to me  i want to start my opensource journey with this awesome project

**Comment by soham1826** [comment]
Hey @AliceWonderland @MysteryHawk17 
 i would love to add this Javascript Calculator , i will add the calculator that can satisfy most of the needs
please assign this project to me i want to start my opensource journey with this awesome project
