### ISSUE TITLE
Display 10 Prime Numbers

### ISSUE THREAD

**Issue by DevDatir** [AliceWonderland/hacktoberfest#11091]
Hello, I would like to contribute to this repo by adding a code to display 10 prime numbers
@AliceWonderland please assign me this issue

Thank You!

**Comment by skillzee** [comment]
I want to contribute please assign me the issue.

**Comment by HarshitaShrivas66** [comment]
Hello, I would like to contribute to this repo, @AliceWonderland please assign me this issue

Thank You!

**Comment by kapiljain15778** [comment]
hello i would like to work on this issue pls assign this task to me 
i will be grateful to you
thank you

**Comment by vipingautam07** [comment]
Please assign me this task as i have good experience and I'm willing to contribute in it.

**Comment by NS220310** [comment]
Hello, I would really appreciate contributing to this repository by adding a code to display 10 prime numbers.
@AliceWonderland Kindly assign the issue to me.
Thank You

**Comment by 2200030361** [comment]
I WOULD REALLY APRECIATE to contrubute to this repository by adding a code to display 10 prime no

**Comment by KalaiselviSelvam21** [comment]
can you assign me this issue?

**Comment by 0sar-44** [comment]
Hello, I would like to contribute to this repo, @AliceWonderland please assign me this issue.

Thank You!

**Comment by D-saksham-gupta** [comment]
Hello, I would like to contribute to this repo,  please assign me this issue.

**Comment by Siddhant-145** [comment]
Hey, Please assign this task to me. I have the experience in this

**Comment by HarshitaShrivas66** [comment]
hey @AliceWonderland  Please accept and merge my pull request and also add hacktoberfest_accepted label

**Comment by Deepanshu123Ban** [comment]
Please assign project to me.

**Comment by senorita17** [comment]
can you assign this project to me

**Comment by MedaAkhil** [comment]
Hi @AliceWonderland i would like to work on this issue. could you please assign this to me

**Comment by Divyagoyal002** [comment]
hello , i would like to contribute to this . please allow me

**Comment by Ashima2003** [comment]
I wish to contribute. Kindly assign me this issue.

**Comment by eeshsaxena** [comment]
assign me this issue i will do it.my leetcode profile-https://leetcode.com/u/eeshsaxena/
