### ISSUE TITLE
Hello World in bhailang

### ISSUE THREAD

**Issue by Umeshkumar24** [AliceWonderland/hacktoberfest#11496]

**Comment by aryanshrivastava08** [comment]
Here is the code for Hello World in BhaiLang @AliceWonderland 

```
hi bhai
 bol bhai "Hello World";
 
  
bye bhai
```

I hope you can merge this

**Comment by VBPMP** [comment]
please, Assign me this issue

**Comment by Ashima2003** [comment]
I wish to contribute. Kindly assign me this issue.
