### ISSUE TITLE
Add a Profile Page

### ISSUE THREAD

**Issue by Ckpuna4** [AliceWonderland/hacktoberfest#182]
Add a ```My_Name.md``` file to the ```profiles``` directory. Use any combination of content and markdown I'd like.

**Comment by ChathuminaVimukthi** [comment]
Added my profile page to profiles directory

**Comment by PREMPRAKASHSINGH** [comment]
@Ckpuna4  Is it still open?
Can i contribute too by adding profile page?

**Comment by Ckpuna4** [comment]
Yes I think. Or you can push here https://github.com/AliceWonderland/hacktoberfest/issues/81

**Comment by AliceWonderland** [comment]
Happy Hacktoberfest! Thanks for contributing!
