### ISSUE TITLE
Multiple entries in CONTRIBUTORS.md

### ISSUE THREAD

**Issue by christianheinrichs** [AliceWonderland/hacktoberfest#1909]
Many entries in the CONTRIBUTORS.md file are duplicated for some reason.

My entry for example appears 4 times. This can either be fixed automatically with a script or manually. If every contributor were to fix this themselves, take a look at pull request #1908, where I removed 3 duplicated entries of my contribution.

**Comment by AliceWonderland** [comment]
Hi Chris, Thanks for notifying me. There's something wrong with the file. There are over 16k lines. Which doesn't seem right.

I will look into this.

In the meantime can we stop merging PRs until I fix this? Thanks!

**Comment by AliceWonderland** [comment]
Ok, it's not just your entry that's duplicated. My entries are duplicated too. 

The first time it happened looks like 3 days ago. Between @robotnamedEmily and @StevenCopeland commits. There's also extra files in the repo that shouldn't be there or are in the wrong folder...

What's confusing too is it looks like many contributors are committing straight into master without creating a PR for review and approval first. I didn't think this was possible unless you're a collaborator. 

If anyone has any suggestions, please let me know. The settings do not allow me to restrict user perms. Only add collaborators and Protect Branches.

**Comment by christianheinrichs** [comment]
@AliceWonderland Hey Alice, normally, users shouldn't have write access to this repository unless they are collaborators like you mentioned (i.e. they have write access), so this is indeed quite peculiar. If this issue persists, you might want to contact GitHub support.

**Comment by StevenCopeland** [comment]
@AliceWonderland I was look at how many contributors there were yesterday(599), and now there are 600. And no PRs have been merged recently!

**Comment by kylesferrazza** [comment]
@AliceWonderland
If a pull request is merged using a "merge commit" (not squashed into one commit), it will appear in the history as if the creator directly pushed to master.

**Comment by shashankKeshava** [comment]
@AliceWonderland  and @christianheinrichs  [Duplicate Contributors Formatter](https://github.com/AliceWonderland/hacktoberfest/pull/3002) solves all your problems

**Comment by christianheinrichs** [comment]
@shashankKeshava In the related issue #2015 you can see that two people already proposed PRs to programmatically sort the CONTRIBUTORS.md file.

I am not sure when the pull requests #2162 (Artur Aciole), #2163 (Artur Aciole), #2197 (Julius Breckel) and your PR #3002 (Shashank Keshava) are going to be reviewed, but I guess we should all wait for Alice's answer.

**Comment by AliceWonderland** [comment]
Thanks @christianheinrichs, @kylesferrazza, @shashankKeshava !

As of Nov 17 the CONTRIBUTORS file has been cleaned and up on master. 

I created a script to remove dupes before I saw these proposals. Which can still be used. I now have to check out the sort and PRs and also resolve merge conflicts for those PRs before I can merge.

We now  have 488 entries instead of 3300. Which doesn't seem quite right given we have 2000+ merges. The bad merges may not only have created dupes but overwritten entries. Hopefully not too many!

I will catch up with what is going on with the sort programs and respond back! Until then please continue to hold off on merges.

Thanks again for all your help and contributions!! :)

**Comment by christianheinrichs** [comment]
@AliceWonderland Glad you got this worked out! Always happy to help.

**Comment by iamabhisekrath** [comment]
HII can you please assign me this issue.
