### ISSUE TITLE
Fix CONTRIBUTORS.md file for duplicates

### ISSUE THREAD

**Issue by AliceWonderland** [AliceWonderland/hacktoberfest#2015]
Until this is sorted out, please do not continue approving, committing, merging!

Thanks!

**Comment by AliceWonderland** [comment]
Until then, if anyone has a suggestion on how best to clean this file, please let me know!

**Comment by StevenCopeland** [comment]
@AliceWonderland To bad! I am not sure how we can do this..... We might have to just look at every single entry to the repo and check a duplicate.

**Comment by AliceWonderland** [comment]
Yeah for now until I can fix the file and make this repo can only be pushed to by collaborators, all merges are on hold.

How are you reviewing, approving, and merging? Through the github.com interface online? Via command line? Or through another client?

I will need time to look at this perhaps sometime next week. In the meantime, I will check for tools out there.

**Comment by StevenCopeland** [comment]
I am doing it all online. I don't actually have a local repository folder.

**Comment by AliceWonderland** [comment]
Yeah, that's what I do for the most part unless I have to move or delete files... Then I update my local repo and update my changes via command line.

**Comment by StevenCopeland** [comment]
@AliceWonderland Do you have any ideas for this?

**Comment by kylesferrazza** [comment]
I'm going to look into this tonight

**Comment by AliceWonderland** [comment]
Hi @StevenCopeland @kylesferrazza !

I have not had a chance to yet. There must be a duplicates finder tool out there. That let's you delete duplicates. I just haven't had a chance to research.

In any case, I put a notice up letting people know there would be no new merges until the contributor file can be sorted out.

In the meantime, a possible option is we could still keep merging but only PRs WITHOUT changes to the CONTRIBUTORS file. Just skip over any PRs that include changes to CONTRIBUTORS files.

I also noticed, the oldes PRs were not getting merged first. If we could make sure those who followed directions and waited patiently for their PRs to be merged that would be great!

**Comment by jbreckel** [comment]
Hey,

I added a script that checks the CONTRIBUTERS file for duplicates and rewrites it with uniques.

This script could be run after every PR to ensure that the file stays unique.

**Comment by artureiji** [comment]
Hi folks, sorry i'm late, didn't see this issue here. I have actually created a script that sorts and remove duplicates for the contributors list the PR is here: 
https://github.com/AliceWonderland/hacktoberfest/pull/2163

And a separate PR for updating the contributors file:
https://github.com/AliceWonderland/hacktoberfest/pull/2162

**Comment by AliceWonderland** [comment]
Thank you @jbreckel and @artureiji !! I am just now catching up to all the comments.

Let me take a look at the status of everything and will reply back to this thread.

In the meantime, if all collaborators can hold off on PR approvals/merges that would be great!

Thanks, Alice

**Comment by shashankKeshava** [comment]
@AliceWonderland  [Duplicate Contributors Formatter](https://github.com/AliceWonderland/hacktoberfest/pull/3002) solves all your problems

**Comment by AliceWonderland** [comment]
Thanks to @jbreckel, @artureiji, and @shashankKeshava !!

I ended up creating a simply py script to remove the duplicate entries since I'm unsure how to run the C program! And would also like to place all these maintenance scripts in a separate script folder independent from the Hello World scripts folder for these programs only.

I'll leave this open for now. PR merges are still on hold until I take some more time to sort this out! Sorry for the delay!!

And appreciate all your help!

**Comment by sadaftahir** [comment]
Hi @AliceWonderland,

How long do you think it can take up to?

**Comment by AliceWonderland** [comment]
Hi @sadaftahir! Sorry for the delay, I haven't been able to commit any time to this. So far I've been approving each PR manually. 

I am looking for ways to automate the approval process since the approval checks are pretty straightforward. The files have to follow the naming convention, be in the correct folder, and the only file that needs to be merged is one basic file.

There are some Command Line Interfaces that may help, but I'm not too familiar with them. Or perhaps Github settings I can put in place that would allow people to auto-merge themselves as long as all requirements are met.

If anyone has any ideas on how to do that, please enter it into the comments. 

Thanks,Alice

**Comment by fineanmol** [comment]
Just Check this Repo Also of Hacktober Fest to win T-shirt ..        [Repo Hacktoberfest2k18](https://github.com/fineanmol/Hacktoberfest2k18)

**Comment by Grenish** [comment]
Hello @AliceWonderland 

I’ve been reviewing the issue concerning duplicate contributor names in our repository, and I believe I have a viable solution that uses GitHub Actions and a bit of Python code to automate the deduplication process.

Proposed Solution:
- **GitHub Actions:** We can set up a workflow that triggers automatically when CONTRIBUTORS.md is modified. This will ensure that our contributor list remains clean and up-to-date without requiring manual intervention.

- **Python Script:** I will develop a Python script (considering different cases) that will intelligently detect and remove duplicate entries, retaining the most complete information for each contributor.

Benefits:
- **Automation:** This solution will eliminate the need for manual checks and updates, saving time and reducing human error.
- **Consistency:** Ensuring the contributor list is free of duplicates will present a more professional and polished appearance to the repository.
- **Transparency:** The automation will be easily visible in the Actions tab, allowing for better tracking of changes made to the contributors' list.

I would love to open a pull request to implement this solution and would be happy to take on this task. Your approval would mean a lot to me!
