### ISSUE TITLE
Add Your Name

### ISSUE THREAD

**Issue by AliceWonderland** [AliceWonderland/hacktoberfest#25]
Add your name to the `CONTRIBUTORS.md` file using the below convention:

```markdown
#### Name: [YOUR NAME](GitHub Link)
- Place: City, State, Country
- Bio: Who are you?
- GitHub: [Your Name](GitHub Link)
```

**Comment by campionfellin** [comment]
@AliceWonderland just added myself, thanks for doing this 👍

**Comment by eculver** [comment]
this is such a great idea. Thanks @AliceWonderland!!

**Comment by agnieszka-miszkurka** [comment]
just made a pull request. Thanks a lot :D
