### ISSUE TITLE
Collaborators See Here - Merging mass

### ISSUE THREAD

**Issue by StevenCopeland** [AliceWonderland/hacktoberfest#2621]
**IMPORTANT** 
To all Collaborators,

We need to hurry with these PRs! There are many left, and not many hours left in the hacktoberfest! We need to merge as many as we can in these last few days!

Regards,
Steven Copeland

**Comment by kylesferrazza** [comment]
(Hacktoberfest only requires making a pull request, not having it merged)

**Comment by StevenCopeland** [comment]
@kylesferrazza That is true. But people like having the PRs merged before the end of the hacktoberfest(personal experience).

**Comment by darkLord19** [comment]
@StevenCopeland @kylesferrazza PRs need to be merged for hacktoberfest

**Comment by AliceWonderland** [comment]
Hello! It's ok to not have these PRs merged before the end of Hacktoberfest!

Ideally, the priority is to have them merged accurately. It looks like files are still being merged to the wrong directory (I see some helloworlds in the root directory) And I see new merges to CONTRIBUTORS.md (which should not be happening unless it has been fixed).

Can we hold off on all approvals/merges again until I can take a look at these files and get them sorted out?

Thanks, Alice
