### ISSUE TITLE
Create a `Hello, World!` Script

### ISSUE THREAD

**Issue by AliceWonderland** [AliceWonderland/hacktoberfest#3]
Add a script to the `scripts` directory in any language of your choice! Here is an example:

```Javascript
// LANGUAGE: Javascript
// ENV: Node.js
// AUTHOR: Alice Chuang
// GITHUB: https://github.com/AliceWonderland

console.log('Hello, World!');
```

**Comment by xorz57** [comment]
C++ doesn't belong to any environment. Can we skip this?

**Comment by redxtech** [comment]
@xorz57 just dont put the env comment. Put the others, but leave `/* ENV: cmake */`  (as an examle) out.

**Comment by xorz57** [comment]
@redxtech That would be fine too!

**Comment by wolframtheta** [comment]
Can I do it in Java?
