### ISSUE TITLE
Will there be a 2019 version with a fresh repository

### ISSUE THREAD

**Issue by koppor** [AliceWonderland/hacktoberfest#5173]
Proposal to start a fresh hacktoberfest repo with the same URL.

1. Rename this repository to hacktoberfest-2017
1. Archive hacktoberfest-2017 (github settings)
2. Create a new repository https://github.com/AliceWonderland/hacktoberfest/ with empty CONTRIBUTORS and profiles

Reason: 

- The 2017 history is properly archived
- 2017 is not mixed with 2019
- newcomers are not confused about the mass of PRs (3731!)

**Comment by vJechsmayr** [comment]
Find a similar repo here:
[https://github.com/vJechsmayr/hacktoberfest2019](https://github.com/vJechsmayr/hacktoberfest2019)

**Comment by koppor** [comment]
@vJechsmayr The idea was to re-use the repository: [Cool URIs don't change](https://www.w3.org/Provider/Style/URI.html).

Moreover, I am against repositories just collecting PRs. See my last bullet point at https://github.com/mattjegan/awesome-hacktoberfest/pull/24.

**Comment by koppor** [comment]
This repository is excluded. See https://github.com/AliceWonderland/hacktoberfest/issues/5296.
