### ISSUE TITLE
I am new to this so i am not too sure if I am doing this correctly.

### ISSUE THREAD

**Issue by hamzahsarwari** [AliceWonderland/hacktoberfest#537]
My attempt at hello world in C++:
__________________________________
#include<iostream>
using namespace std;
int main(){
cout << "Hello World!";
return 0;
}

**Comment by smb564** [comment]
Hi @hamzahsarwari , I think your hello world misses what is imported. You should add `#include <iostream>`

And for the rest of the tasks please go through the readme file. It explains the tasks very nicely.

**Comment by AliceWonderland** [comment]
Hi @hamzahsarwari, 

Thanks for your comment! I don't know C++ very well however, please add some comments at the top listing what language you're using, your name (author), and any helpful links you'd like to provide!

See the README for a comments example!
Thanks, Alice
