### ISSUE TITLE
Other hacktoberfest starter repo

### ISSUE THREAD

**Issue by ezralazuardy** [AliceWonderland/hacktoberfest#5467]
https://github.com/ezralazuardy/hacktoberfest

**Comment by koppor** [comment]
The repository is archived. I think, it was regarded as spam.

**Comment by ezralazuardy** [comment]
it's now opened :)

**Comment by Iqlaas** [comment]
@koppor, yup. if create PR it won't be counted as well.

**Comment by ezralazuardy** [comment]
;)
