### ISSUE TITLE
Hacktoberfest contribute here

### ISSUE THREAD

**Issue by vijaygupta18** [AliceWonderland/hacktoberfest#8110]
For easy contribution create pr on this repo.

https://github.com/vijaygupta18/Hacktoberfest-2021

**Comment by fineanmol** [comment]
October Fest only completed, when your pull request merge.
Make a contribution on https://github.com/fineanmol/Hacktoberfest2k21 to confirm merge to master branch ✨

**Comment by riya244** [comment]
hi, i want to contribute in this issue, please assign me this issue @fineanmol
