### ISSUE TITLE
add contributing.md

### ISSUE THREAD

**Issue by khareyash05** [AliceWonderland/hacktoberfest#8156]
I would like to add contributing.md

**Comment by byteknower** [comment]
Danda Umasai Anvesh Reddy

**Comment by fineanmol** [comment]
October Fest only completed, when your pull request merge.
Make a contribution on https://github.com/fineanmol/Hacktoberfest2k21 to confirm merge to master branch ✨

**Comment by codetravellearn** [comment]
please review my PR  #8992
