### ISSUE TITLE
Contribution request

### ISSUE THREAD

**Issue by joe-pierre** [AliceWonderland/hacktoberfest#9265]
Hi, I want to be a contributor !

**Comment by abhishek-munda** [comment]
Please read and follow the contribution guide provided in README.md file and make a PR to contribute.

**Comment by joe-pierre** [comment]
Thanks ! I'm doing it. 👍

**Comment by Diptenusarkar** [comment]
> Hi, I want to be a contributor!
You can contribute to my rep.
All reps are pinned in my profile.
