### ISSUE TITLE
new should make index .js more better

### ISSUE THREAD

**Issue by Ashiiidev** [AliceWonderland/hacktoberfest#9298]
help me

**Comment by Ashiiidev** [comment]
and you should foccasing on adding more and more finction

**Comment by kartikver15gr8** [comment]
What is this issue all about tell me??

**Comment by Ashiiidev** [comment]
It is about your make website more beautiful and cool

**Comment by Ashiiidev** [comment]
I your add your profile page or you can help in making website beautiful

**Comment by anmol111pal** [comment]
Hey, please assign me this task.
